name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  push_to_registry:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2


      #      - name: Build php:7.4.10 Docker image
      #        run: docker build --file docker-configs/dockerfiles/php7.4.10-fpm --tag php:7.4.10 .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Pull existing images to skip non changed layers
        run: docker pull ghcr.io/danielpetrica/php -a

      - name: build php:7.4.10
        run: docker build -f dockerfiles/php7.4.10-fpm.dockerfile --tag 'ghcr.io/danielpetrica/php:7.4.10' .

      - name: build php:7.3.3
        run: docker build -f dockerfiles/php7.3.3-fpm.dockerfile --tag 'ghcr.io/danielpetrica/php:7.3.3' .

      - name: build php:7.3.3-composer1
        run: docker build -f dockerfiles/php7.3.3-fpm-composer1.dockerfile --tag 'ghcr.io/danielpetrica/php:7.3.3-composer1' .

      - name: build php:7.4.8
        run: docker build -f dockerfiles/php7.4.8-fpm.dockerfile --tag 'ghcr.io/danielpetrica/php:7.4.8' .

      - name: build php:7.4.10-mongo
        run: docker build -f dockerfiles/php7.4.10-mongo-fpm.dockerfile --tag 'ghcr.io/danielpetrica/php:7.4.10-mongo' .


      - name: build php:7.2.24
        run: docker build -f dockerfiles/php7.2.24-fpm.dockerfile  --tag ghcr.io/danielpetrica/php:7.2.24 .

      - name: build php:7.1.30-composer1
        run: docker build -f dockerfiles/php7.1.30-fpm-composer1.dockerfile  --tag ghcr.io/danielpetrica/php:7.1.30-composer1 .

      - name: build php:7.1.30
        run: docker build -f dockerfiles/php7.1.30-fpm.dockerfile  --tag ghcr.io/danielpetrica/php:7.1.30 .

      - name:  and push php:7.4.8
        run:  docker push ghcr.io/danielpetrica/php:7.4.8

      - name:  and push php:7.4.10
        run:  docker push ghcr.io/danielpetrica/php:7.4.10

      - name:  and push php:7.3.3
        run:  docker push ghcr.io/danielpetrica/php:7.3.3

      - name:  and push php:7.3.3-composer1
        run:  docker push ghcr.io/danielpetrica/php:7.3.3-composer1


      - name:  and push php:7.4.10-mongo
        run:  docker push ghcr.io/danielpetrica/php:7.4.10-mongo

      - name:  and push php:7.2.24
        run:  docker push ghcr.io/danielpetrica/php:7.2.24

      - name:  and push php:7.1.30
        run:  docker push ghcr.io/danielpetrica/php:7.1.30

      - name:  and push php:7.1.30-composer1
        run:  docker push ghcr.io/danielpetrica/php:7.1.30-composer1


#       - name: Push to Github
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./docker-configs/dockerfiles/php7.4.10-fpm
#           push: true
#           tags: ghcr.io/danielpetrica/php:7.4.10
